user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log          /var/log/nginx/access.log main;
    sendfile            on;
    keepalive_timeout   65;

    # used in scenario 5 - A/B testing:
    split_clients  "${time_iso8601}" $a_or_b {
        50%     siteA;
        50%     siteB;
    }

    # scenario 7 - compress the response body using gzip
    gzip  on;

    server {
        listen 80 default_server;
        server_name localhost;
        
        # scenario 1 - serve static files from /out directory
        root /out;  

        # scenario 2 - return the request URI as a response
        location /inspect {
            add_header Content-Type text/plain;
            return 200 "$request_uri";
        }

        #scenario 3 - replace all requests for .jpg or .jpeg files with a 301 redirect to /logo-2.png
        location ~* \.jpe?g$ {
            return 301 /logo-2.png;
        }

        #scenario 4 - rewrite all requests starting with /old/ to remove the /old/ prefix
        location /old/ {
            rewrite ^/old/(.*)$ /$1;
        }

        #scenario 5 - A/B testing: serve different content based on the request URI
        location /site {            
            return 302 /$a_or_b;
        }
        location /siteA {
            add_header Content-Type text/plain;
            return 200 "A Experience!";
        }
        location /siteB {
            add_header Content-Type text/plain;
            return 200 "B Experience!";
        }

        # scenario 6 - modify the response body
        location / {
            sub_filter 'About This Page' 'About This Page - Modified by Nginx';
            sub_filter_once off;
        }

        # scenario 8 - return the request URI as a response overwriting all headers
        location /inspect2 {
            default_type text/plain;
            return 200 "$request_uri";
        }
    }
}